// ==========================================
// 1. BASE DE DATOS UNIFICADA DE JUEGOS (GAME_TAGS)
// ==========================================
const GAME_TAGS = {
  // --- # ---
  "1000xRESIST": ["horror", "rpg", "summer", "narrativo", "sci-fi", "only-english"],
  "88 Heroes": ["plataformas", "accion", "2d", "comedia", "retro", "indie", "singleplayer"],
  "9 Years of Shadows": ["horror", "narrativo", "aventura", "2D", "misterio", "atmosfera", "pixelart", "retro", "indie", "singleplayer", "only-english"],

  // --- A ---
  "A Boy and His Blob": ["plataformas", "puzles", "aventura", "cooperativo-ia", "fantasia", "exploracion", "2d", "cozy", "singleplayer", "indie"],
  "A Hat in Time": ["summer", "cozy", "plataformas", "aventura", "humor"],
  "A Little to the Left": ["summer", "cozy", "puzzle", "relajante", "humor"],
  "A Plague Tale: Innocence": ["horror", "narrativo", "aventura", "accion", "atmosfera"],
  "A Plague Tale: Requiem": ["narrativo", "tenso", "atmosfera", "puzzle", "misterio", "aventura", "dificil"],
  "A Short Hike": ["summer", "cozy", "exploracion", "narrativo", "relajante"],
  "Abyss Odyssey": ["accion", "roguelike", "beat-em-up", "plataformas", "fantasia", "exploracion", "combate", "metroidvania-lite", "singleplayer", "coop"],
  "Abzû": ["summer", "cozy", "exploracion", "atmosfera", "relajante"],
  "Accounting+": ["summer", "humor", "vr", "corto", "aventura"],
  "Aces of the Luftwaffe": ["shooter", "arcade", "matamarcianos", "scroll-vertical", "aviacion", "segunda-guerra-mundial", "accion", "singleplayer", "coop"],
  "Action Henk": ["plataformas", "velocidad", "carreras", "arcade", "precision", "fisica", "competitivo", "multijugador", "singleplayer", "indie"],
  "Actual Sunlight": ["narrativo", "visual-novel", "drama", "realista", "melancolico", "singleplayer"],
  "ADOM": ["roguelike", "rpg", "dungeon-crawler", "por-turnos", "fantasia", "supervivencia", "permadeath", "textual", "hardcore", "singleplayer"],
  "Adventures of Pip": ["plataformas", "puzles", "retro", "evolucion-grafica", "accion", "indie", "singleplayer"],
  "Aeterna Noctis": ["metroidvania", "soulslike", "accion", "plataformas", "exploracion", "desafiante", "fantasia", "singleplayer"],
  "Affordable Healthcare": ["clicker", "idle", "gestion", "defensa-de-torres", "accion", "progresion", "skill-tree", "ciencia", "biologia", "singleplayer", "indie", "only-english"],
  "Afterparty": ["aventura", "narrativo", "humor", "decisiones", "singleplayer"],
  "Against the Storm": ["strategy", "horror", "roguelite", "gestion", "construccion", "only-english"],
  "Agatha Knife": ["aventura-grafica", "humor-negro", "narrativo", "point-and-click", "satira", "2d", "indie", "singleplayer"],
  "Age of Wonders": ["estrategia", "4x", "rpg", "fantasia", "turnos", "gestion", "singleplayer"],
  "Age of Wonders 4": ["estrategia", "4x", "rpg", "fantasia", "turnos", "gestion", "creacion-personajes", "singleplayer"],
  "Aground": ["rpg", "supervivencia", "crafting", "mineria", "gestion", "progresion", "indie", "singleplayer"],
  "Airships: Conquer the Skies": ["estrategia", "construccion", "sandbox", "combate", "steampunk", "simulacion", "gestion", "indie", "singleplayer", "multijugador"],
  "Akane": ["cyberpunk", "summer", "accion", "pixelart", "dificil", "only-english"],
  "Alba: A Wildlife Adventure": ["summer", "cozy", "exploracion", "narrativo", "relajante"],
  "Alaloth: Champions of The Four Kingdoms": ["rpg", "accion", "isometrico", "fantasia", "combate", "exploracion", "indie", "singleplayer"],
  "Aldersblood": ["rpg", "tactico", "fantasia-oscura", "turnos", "estrategia", "indie", "singleplayer"],
  "Alekon": ["captura-de-fotos", "exploracion", "relajante", "sandbox", "coleccion", "aventura", "indie", "singleplayer"],
  "Alice is Dead": ["aventura", "puzles", "point-and-click", "surrealista", "horror", "singleplayer", "only-english"],
  "Alicia Griffith: Lakeside Murder": ["aventura", "misterio", "investigacion", "narrativo", "puzles", "singleplayer"],
  "Alien Hominid": ["accion", "run-and-gun", "arcade", "plataformas", "2d", "coop", "humor", "indie"],
  "Alien Swarm": ["shooter", "cooperativo", "tactico", "top-down", "accion", "sci-fi", "multijugador", "only-english", "free"],
  //"Alien: Isolation": ["horror", "survival", "sci-fi", "sigilo", "tenso"],
  "All That Remains: Part 1": ["aventura", "puzles", "escape-room", "narrativo", "singleplayer"],
  "Alpha Polaris": ["horror", "aventura", "narrativo", "misterio", "atmosfera", "singleplayer", "only-english", "free"],
  "Alruna: End Of History": ["rpg", "pixelart", "aventura", "fantasia", "narrativo"],
  "Alto's Odyssey": ["cozy", "relajante", "plataformas", "artístico", "atmosfera"],
  "Aluna: Sentinel of the Shards": ["rpg", "accion", "mitologia", "aventura", "fantasia", "singleplayer", "only-english"],
  "Alwa's Awakening": ["metroidvania", "plataformas", "retro", "pixelart", "exploracion", "dificil", "indie", "singleplayer"],
  "Alwa's Legacy": ["metroidvania", "plataformas", "exploracion", "pixelart", "aventura", "mejorado", "indie", "singleplayer"],
  "Always Sometimes Monsters": ["narrativo", "rpg", "decisiones", "drama", "vida-real", "aventura", "indie", "singleplayer", "only-english"],
  "Amazing Princess Sarah": ["plataformas", "accion", "hack-and-slash", "retro", "indie", "singleplayer", "only-english"],
  "Ambition of the Slimes": ["estrategia", "turnos", "tactico", "fantasia", "slimes", "rpg", "indie", "singleplayer", "only-english"],
  "Ambition: A Minuet in Power": ["narrativo", "visual-novel", "romance", "intriga", "drama", "estrategia-social", "historia", "revolucion-francesa", "indie", "singleplayer", "only-english"],
  "American Arcadia": ["puzles", "plataformas", "narrativo", "distopia", "singleplayer"],
  "Amnesia: A Machine for Pigs": ["horror", "atmosfera", "narrativo", "misterio", "singleplayer"],
  "Amnesia: Rebirth": ["horror", "atmosfera", "narrativo", "exploracion", "misterio", "singleplayer"],
  "Amnesia: The Bunker": ["horror", "summer", "survival", "misterio", "tenso"],
  "Amnesia: The Dark Descent": ["horror", "atmosfera", "narrativo", "exploracion", "misterio", "singleplayer"],
  "Among Ripples": ["simulacion", "gestion", "relax", "cozy", "ecologia", "singleplayer", "free", "only-english"],
  "Among the Sleep": ["terror", "survival", "primera-persona", "psicologico", "aventura", "infancia", "narrativo", "singleplayer", "indie"],
  "Among Us": ["social", "multijugador", "online", "deduccion", "party", "casual", "coop"],
  "An Airport for Aliens Currently Run by Dogs": ["aventura", "humor", "surrealista", "exploracion", "singleplayer", "only-english"],
  "Anarcute": ["accion", "destruccion", "multitud", "arcade", "caos", "fisica", "indie", "singleplayer"],
  "Ancestors Legacy": ["estrategia", "tiempo-real", "rts", "combate", "medieval", "historia", "gestion", "singleplayer", "multijugador"],
  "Ancestors: The Humankind Odyssey": ["supervivencia", "exploracion", "simulacion", "aventura", "narrativo", "singleplayer"],
  "Ancient Enemy": ["puzles", "cartas", "estrategia", "fantasia", "turnos", "singleplayer", "only-english"],
  "And Yet It Moves": ["puzles", "plataformas", "fisica", "indie", "singleplayer"],
  "Anemoiapolis": ["horror", "puzzle", "liminal", "exploracion", "atmosfera"],
  "Angel Engine": ["horror", "simulacion", "puzles", "atmosfera", "narrativo", "sci-fi", "distopico", "singleplayer", "indie", "only-english"],
  "Anger Foot": ["accion", "arcade", "shooter", "humor", "rapido", "singleplayer"],
  "Angry Penguin": ["puzles", "fisica", "arcade", "casual", "movil", "competitivo", "retro", "nostalgico", "singleplayer"],
  "Animal Well": ["horror", "puzzle", "cozy", "metroidvania", "exploracion"],
  "Anno": ["estrategia", "gestion", "city-builder", "economia", "historia", "colonizacion", "tiempo-real", "sandbox", "singleplayer", "multijugador"],
  "Anodyne": ["aventura", "exploracion", "puzles", "surrealista", "psicologico", "zelda-like", "2d", "pixelart", "indie"],
  "Anodyne 2: Return to Dust": ["aventura", "exploracion", "puzles", "surrealista", "psicologico", "narrativo", "2d", "3d", "indie"],
  "Another World": ["aventura", "plataformas", "narrativo", "cinematico", "retro", "singleplayer"],
  "Antichamber": ["summer", "puzzle", "exploracion", "dificil", "atmosfera"],
  "Ape Out": ["accion", "arcade", "beat-em-up", "musical", "violencia-estilizada", "top-down", "indie"],
  "Apocalipsis": ["puzles", "point-and-click", "aventura", "arte-medieval", "oscuro", "indie", "singleplayer"],
  "Apparition": ["horror", "exploracion", "mundo-abierto", "caza-fantasmas", "singleplayer", "only-english"],
  "Aqua Kitty: Milk Mine Defender": ["shooter", "arcade", "submarino", "defensa", "2d", "indie", "retro", "coop", "only-english"],
  "Aquaria": ["summer", "cozy", "metroidvania", "exploracion", "only-english"],
  "Ara Fell": ["summer", "rpg", "narrativo", "pixelart", "aventura"],
  "Aragami": ["sigilo", "accion", "ninja", "fantasia", "tercera-persona", "coop", "indie"],
  "Aragami 2": ["sigilo", "accion", "ninja", "combate", "tercera-persona", "coop", "indie"],
  "Arcadecraft": ["gestion", "simulacion", "retro", "economia", "singleplayer", "only-english"],
  "Arcadian Atlas": ["rpg", "strategy", "summer", "pixelart", "tactico"],
  "Arcania": ["rpg", "accion", "fantasia", "mundo-abierto", "aventura", "singleplayer"],
  "Arcanium: Rise of Akhan": ["roguelike", "deckbuilder", "cartas", "estrategia", "fantasia", "turnos", "singleplayer", "indie"],
  "Armello": ["estrategia", "mesa-digital", "cartas", "turnos", "fantasia", "multijugador", "singleplayer", "rpg", "rol-social"],
  "Armikrog": ["aventura-grafica", "claymation", "point-and-click", "puzles", "surrealista", "indie", "singleplayer"],
  "Art of Rally": ["summer", "simulacion", "relajante", "artístico", "cozy"],
  "Ary and the Secret of Seasons": ["aventura", "accion", "plataformas", "fantasia", "exploracion", "singleplayer"],
  "Asdivine Hearts": ["jrpg", "rpg", "turnos", "fantasia", "anime", "narrativo", "indie", "singleplayer", "only-english"],
  "Asguaard": ["rpg", "fantasia", "turnos", "clasico", "aventura", "indie", "singleplayer", "only-english"],
  "Ash of Gods: Redemption": ["rpg", "tactico", "turnos", "narrativo", "decisiones", "fantasia", "indie", "singleplayer"],
  "Ashen": ["rpg", "accion", "soulslike", "mundo-abierto", "exploracion", "minimalista", "coop"],
  "Assault Android Cactus": ["shooter", "twin-stick", "arcade", "accion", "coop", "bullet-hell", "indie", "multijugador"],
  "Assemble with Care": ["cozy", "puzzle", "narrativo", "relajante", "corto"],
  "Astalon: Tears of the Earth": ["metroidvania", "plataformas", "accion", "fantasia", "exploracion", "pixelart", "retro", "dificil", "singleplayer", "indie", "only-english"],
  "Astebreed: Definitive Edition": ["shooter", "bullet-hell", "arcade", "accion", "mechas", "ciencia-ficcion", "3d", "scroll", "indie", "singleplayer", "only-english"],
  "Asterigos: Curse of the Stars": ["rpg", "accion", "soulslike", "fantasia", "aventura", "tercera-persona", "exploracion", "combate", "singleplayer", "indie"],
  "Astor: Blade of the Monolith": ["accion", "rpg", "hack-and-slash", "aventura", "fantasia", "plataformas", "exploracion", "combate", "singleplayer", "indie"],
  "Astro Duel": ["accion", "multijugador", "shooter", "espacial", "local", "competitivo", "only-english"],
  "Astro Duel 2": ["accion", "plataformas", "shooter", "espacial", "multijugador", "local", "only-english"],
  "Astrologaster": ["narrativo", "humor", "visual-novel", "historico", "singleplayer", "only-english"],
  "Atelier": ["jrpg", "rpg", "crafting", "alquimia", "narrativo", "anime", "gestion", "turnos", "exploracion", "singleplayer"],
  "Athenian Rhapsody": ["rpg", "humor", "narrativo", "aventura", "singleplayer", "only-english"],
  "ATOM RPG": ["rpg", "postapocaliptico", "turnos", "supervivencia", "exploracion", "fallout-like", "indie", "singleplayer"],
  "Atomicrops": ["roguelike", "accion", "farming", "simulacion", "bullet-hell", "supervivencia", "gestion", "pixelart", "indie", "singleplayer"],
  "Attentat 1942": ["narrativo", "historico", "aventura", "educativo", "singleplayer"],
  "Audiosurf": ["puzles", "musical", "ritmico", "arcade", "singleplayer", "only-english"],
  "Audiosurf 2": ["puzles", "musical", "ritmico", "arcade", "singleplayer", "only-english"],
  "Autonauts": ["simulacion", "automatizacion", "gestion", "sandbox", "crafting", "estrategia", "programacion-basica", "cozy", "indie", "singleplayer"],
  "Aven Colony": ["simulacion", "gestion", "city-builder", "estrategia", "ciencia-ficcion", "colonizacion", "supervivencia", "singleplayer", "indie"],
  "Axiom Verge": ["metroidvania", "ciencia-ficcion", "exploracion", "retro", "2d", "pixelart", "indie"],
  "Axiom Verge 2": ["metroidvania", "ciencia-ficcion", "exploracion", "retro", "2d", "pixelart", "indie"],
  "Aztez": ["accion", "beat-em-up", "estrategia", "turnos", "historia", "azteca", "combate", "violencia-estilizada", "indie", "singleplayer"],

  // --- B ---
  "Baba Is You": ["summer", "puzzle", "creativo", "dificil", "pixelart"],
  "Backpack Hero": ["roguelike", "gestion", "inventario", "turnos", "estrategia", "indie", "singleplayer", "only-english"],
  "Bad North": ["estrategia", "tactico", "minimalista", "roguelike", "defensa", "indie", "singleplayer"],
  "Bad North: Jotunn Edition": ["estrategia", "tactico", "minimalista", "roguelike", "defensa", "indie", "singleplayer"],
  "Balatro": ["summer", "strategy", "cartas", "roguelite", "humor"],
  "Banished": ["gestion", "construccion", "estrategia", "supervivencia", "simulacion", "indie", "singleplayer", "only-english"],
  "Baro Kart": ["carreras", "conduccion", "arcade", "multijugador", "indie", "casual", "only-english"],
  "Barony": ["roguelike", "rpg", "primera-persona", "mazmorras", "cooperativo", "indie", "multijugador", "only-english"],
  "Barotrauma": ["horror", "strategy", "cooperativo", "survival", "submarino"],
  "Bastion": ["rpg", "accion", "isometrico", "narrativo", "fantasia", "indie", "singleplayer"],
  "Battle Brothers": ["rpg", "tactico", "turnos", "estrategia", "gestion", "indie", "singleplayer"],
  "BattleBlock Theater": ["plataformas", "cooperativo", "comedia", "puzles", "accion", "indie", "multijugador"],
  "Beacon": ["shooter", "roguelike", "accion", "ciencia-ficcion", "isometrico", "indie", "singleplayer"],
  "Beacon Pines": ["horror", "cozy", "narrativo", "aventura", "puzzle"],
  "Bear and Breakfast": ["gestion", "construccion", "relajante", "rol", "simulacion", "indie", "singleplayer"],
  "Beastro": ["cozy", "gestion", "simulacion", "fantasia", "multijugador"],
  "Before We Leave": ["gestion", "construccion", "estrategia", "relajante", "espacial", "indie", "singleplayer"],
  "Bendy and the Dark Revival": ["terror", "primera-persona", "puzles", "accion", "narrativo", "indie", "singleplayer"],
  "Bendy and the Ink Machine": ["terror", "primera-persona", "puzles", "accion", "narrativo", "indie", "singleplayer"],
  "Besiege": ["construccion", "fisicas", "destruccion", "sandbox", "estrategia", "indie", "singleplayer"],
  "Biomutant": ["summer", "rpg", "accion", "exploracion", "aventura"],
  "Bionic Commando": ["accion", "plataformas", "disparos", "retro", "clasico", "singleplayer"],
  "Bionic Commando Rearmed": ["accion", "plataformas", "disparos", "retro", "clasico", "singleplayer"],
  "Biotonic Bay": ["rpg", "accion", "aventura", "indie", "singleplayer"],
  "Biped": ["cooperativo", "puzles", "plataformas", "fisicas", "familiar", "indie", "multijugador"],
  "Bite the Bullet": ["rpg", "accion", "plataformas", "disparos", "roguelite", "indie", "singleplayer"],
  "Black Future '88": ["roguelike", "accion", "cyberpunk", "plataformas", "disparos", "indie", "singleplayer", "only-english"],
  "Black the Fall": ["puzles", "plataformas", "distopia", "atmosferico", "oscuro", "indie", "singleplayer"],
  "Blair Witch": ["terror", "psicologico", "primera-persona", "misterio", "atmosferico", "indie", "singleplayer"],
  "Blasphemous": ["horror", "soulslike", "pixelart", "plataformas", "dificil"],
  "Blasphemous 2": ["metroidvania", "accion", "souls-like", "fantasia-oscura", "plataformas", "indie", "singleplayer"],
  "Blazing Chrome": ["accion", "plataformas", "disparos", "retro", "arcade", "indie", "singleplayer"],
  "Bleed": ["accion", "plataformas", "disparos", "arcade", "indie", "singleplayer", "only-english"],
  "Bleed 2": ["accion", "plataformas", "disparos", "arcade", "indie", "singleplayer", "only-english"],
  "Blighted": ["horror", "summer", "accion", "roguelite", "pixelart"],
  "Block'hood": ["gestion", "construccion", "simulacion", "ecologia", "estrategia", "indie", "singleplayer"],
  "Blood West": ["shooter", "terror", "primera-persona", "sigilo", "retro", "indie", "singleplayer"],
  "Bloodstained: Ritual of the Night": ["metroidvania", "accion", "plataformas", "fantasia", "rol", "indie", "singleplayer"],
  "Blue Prince": ["puzzle", "misterio", "strategy", "roguelite", "atmosfera", "only-english"],
  "Bo: Path of the Teal Lotus": ["metroidvania", "plataformas", "accion", "mitologia", "fantasia", "indie", "singleplayer"],
  "Book of Demons": ["hack-and-slash", "cartas", "rpg", "isometrico", "mazmorras", "indie", "singleplayer"],
  "Book of Travels": ["rpg", "exploracion", "multijugador", "rol", "fantasia", "indie", "aventura"],
  "Botanicula": ["aventura", "point-and-click", "puzles", "exploracion", "fantasia", "indie", "singleplayer"],
  "Botany Manor": ["cozy", "puzzle", "relajante", "narrativo", "artístico"],
  "Boyfriend Dungeon": ["rpg", "roguelite", "narrativo", "romance", "humor"],
  "BPM: BULLET PER MINUTE": ["shooter", "ritmo", "roguelike", "accion", "primera-persona", "indie", "singleplayer"],
  "Braid": ["summer", "puzzle", "plataformas", "narrativo", "artístico"],
  "Bramble: The Mountain King": ["horror", "plataformas", "aventura", "narrativo", "atmosfera"],
  "Bread & Fred": ["cooperativo", "plataformas", "humor", "dificil", "pixelart"],
  "Bridge Constructor": ["puzles", "fisicas", "construccion", "simulacion", "indie", "singleplayer"],
  "Bridge Constructor Portal": ["puzles", "fisicas", "construccion", "ciencia-ficcion", "indie", "singleplayer"],
  "Broforce": ["accion", "plataformas", "cooperativo", "destruccion", "disparos", "indie", "multijugador"],
  "Brotato": ["roguelike", "accion", "disparos", "arena", "supervivencia", "indie", "singleplayer"],
  "Brothers: A Tale of Two Sons": ["aventura", "narrativo", "puzles", "emotivo", "fantasia", "indie", "singleplayer"],
  "Bubsy: The Woolies Strike Back": ["plataformas", "accion", "clasico", "retro", "aventura", "singleplayer"],
  "Buckshot Roulette": ["horror", "puzzle", "tenso", "misterio", "corto"],
  "Bug Fables: The Everlasting Sapling": ["rpg", "turnos", "aventura", "fantasia", "exploracion", "indie", "singleplayer"],
  "Bugsnax": ["aventura", "exploracion", "puzles", "narrativo", "misterio", "indie", "singleplayer"],
  "Bum Simulator": ["simulacion", "comedia", "mundo-abierto", "accion", "primera-persona", "indie", "singleplayer"],
  "Bunhouse": ["cozy", "summer", "simulacion", "relajante", "humor"],
  "Bzzzt": ["plataformas", "accion", "retro", "precision", "rapido", "indie", "singleplayer"],

  // --- C ---
  // --- C ---
  "Cairn": ["simulador", "tenso", "atmosfera", "survival", "dificil", "aventura"],
  "Calx": ["summer", "cozy", "puzzle", "relajante", "artístico"],
  "Carrion": ["horror", "accion", "metroidvania", "artístico", "humor"],
  "Carto": ["summer", "cozy", "puzzle", "narrativo", "exploracion"],
  "Cassette Beasts": ["rpg", "cozy", "summer", "pixelart", "exploracion"],
  "Caves of Qud": ["rpg", "sci-fi", "roguelite", "exploracion", "only-english"],
  "Celeste": ["summer", "plataformas", "narrativo", "dificil", "artístico"],
  "Chained Echoes": ["summer", "rpg", "pixelart", "narrativo", "aventura"],
  "Chants of Sennaar": ["summer", "puzzle", "narrativo", "misterio", "artístico"],
  "Chicory: A Colorful Tale": ["cozy", "aventura", "puzzle", "artístico", "narrativo"],
  "Children of the Sun": ["horror", "puzzle", "accion", "narrativo", "dificil"],
  "Citizen Sleeper": ["rpg", "cyberpunk", "cozy", "narrativo", "sci-fi"],
  "Clair Obscur: Expedition 33": ["rpg", "narrativo", "accion", "artístico", "emocional"],
  "Cloud Gardens": ["summer", "cozy", "puzzle", "relajante", "creativo"],
  "Cloud Meadow": ["cozy", "rpg", "simulacion", "gestion", "construccion"],
  "Cloudheim": ["cozy", "summer", "rpg", "exploracion", "construccion"],
  "Cloudpunk": ["cyberpunk", "summer", "narrativo", "pixelart", "atmosfera"],
  "Cocoon": ["puzzle", "exploracion", "atmosfera", "artístico", "sci-fi"],
  "Coffee Talk": ["cozy", "summer", "narrativo", "relajante", "visual-novel"],
  "Color Fear": ["horror", "psicologico", "puzzle", "atmosfera", "misterio"],
  "Coral Island": ["summer", "cozy", "simulacion", "rpg", "relajante"],
  "Core Keeper": ["summer", "cozy", "survival", "construccion", "cooperativo"],
  "Cozy Grove": ["summer", "cozy", "simulacion", "narrativo", "relajante"],
  "CrossCode": ["summer", "rpg", "accion", "puzzle", "pixelart"],
  "Crow Country": ["horror", "puzzle", "pixelart", "retro", "misterio"],
  "Crushed in Time": ["sci-fi", "accion", "aventura", "plataformas", "pixelart"],
  "Cult of the Lamb": ["horror", "cozy", "strategy", "roguelite", "gestion"],
  "Cuphead": ["summer", "accion", "plataformas", "retro", "dificil"],
  "Curse of the Dead Gods": ["horror", "roguelite", "accion", "dificil", "pixelart"],
  "Cursemark": ["horror", "accion", "soulslike", "fantasia", "oscuro"],

  // --- D ---
  "D-topia": ["summer", "cozy", "construccion", "relajante", "pixelart"],
  "Dark Scrolls": ["rpg", "fantasia", "oscuro", "aventura", "exploracion"],
  "Darkwood": ["horror", "survival", "atmosfera", "tenso", "pixelart"],
  "Dave the Diver": ["summer", "cozy", "accion", "gestion", "aventura"],
  "Dead Cells": ["summer", "roguelite", "accion", "metroidvania", "dificil"],
  "Deep Rock Galactic": ["summer", "accion", "cooperativo", "shooter", "humor"],
  "Demon Turf": ["summer", "plataformas", "accion", "pixelart", "humor"],
  "Denshattack!": ["accion", "arcade", "retro", "pixelart", "indie"],
  "Dicey Dungeons": ["summer", "roguelite", "cartas", "strategy", "humor"],
  "Dinkum": ["summer", "cozy", "simulacion", "gestion", "exploracion"],
  "Disco Elysium": ["horror", "summer", "rpg", "narrativo", "detectivesco"],
  "Doki Doki Literature Club": ["horror", "cozy", "narrativo", "visual-novel", "pixelart"],
  "Don't Let It Starve": ["survival", "gestion", "horror", "cooperativo", "indie"],
  "Donut County": ["summer", "cozy", "puzzle", "humor", "narrativo"],
  "Dordogne": ["summer", "cozy", "narrativo", "aventura", "artístico"],
  "Dredge": ["horror", "summer", "cozy", "pesca", "misterio"],
  "Dusk": ["horror", "summer", "accion", "retro", "shooter"],

  // --- E ---
  "Eastshade": ["summer", "cozy", "exploracion", "narrativo", "artístico"],
  "Endling: Extinction is Forever": ["aventura", "narrativo", "emocional", "atmosfera", "survival"],
  "Enter the Gungeon": ["summer", "accion", "roguelite", "shooter", "pixelart"],
  "Everhood": ["rpg", "rítmico", "artístico", "narrativo", "surrealista"],
  "Everything": ["summer", "cozy", "relajante", "filosófico", "artístico"],

  // --- F ---
  "Factorio": ["strategy", "gestion", "construccion", "simulacion", "dificil"],
  "Faith: The Unholy Trinity": ["horror", "pixelart", "retro", "misterio", "atmosfera"],
  "FAR: Changing Tides": ["aventura", "cozy", "atmosfera", "narrativo", "artístico"],
  "FAR: Lone Sails": ["aventura", "cozy", "atmosfera", "narrativo", "artístico"],
  "Fez": ["summer", "puzzle", "plataformas", "exploracion", "pixelart"],
  "Firewatch": ["summer", "narrativo", "exploracion", "misterio", "atmosfera"],
  "Florence": ["narrativo", "cozy", "puzzle", "emocional", "corto"],
  "Flower": ["summer", "cozy", "relajante", "atmosfera", "artístico"],
  "Fran Bow": ["horror", "aventura", "puzzle", "narrativo", "psicologico"],
  "Frostpunk 2": ["strategy", "horror", "gestion", "survival", "narrativo"],

  // --- G ---
  "Garden Story": ["summer", "cozy", "rpg", "aventura", "pixelart"],
  "Gastova: The Witches of Arkana": ["rpg", "fantasia", "aventura", "narrativo", "exploracion"],
  "Ghostrunner 2": ["cyberpunk", "summer", "accion", "plataformas", "dificil"],
  "Gibbon: Beyond the Trees": ["cozy", "artístico", "relajante", "plataformas", "narrativo"],
  "Gloomwood": ["horror", "sigilo", "accion", "atmosfera", "retro"],
  "Goat Simulator": ["summer", "humor", "sandbox", "cooperativo", "surrealista"],
  "Goat Simulator 2": ["summer", "humor", "sandbox", "cooperativo", "surrealista"],
  "Goat Simulator 3": ["summer", "humor", "sandbox", "cooperativo", "surrealista"],
  "Gombo": ["aventura", "accion", "plataformas", "indie", "humor"],
  "Goodbye Volcano High": ["narrativo", "visual-novel", "emocional", "rítmico", "aventura"],
  "Gorm": ["horror", "puzzle", "misterio", "atmosfera", "corto"],
  "Gothic 1 Remake": ["rpg", "fantasia", "exploracion", "accion", "aventura"],
  "Grave Seasons": ["horror", "cozy", "summer", "simulacion", "only-english"],
  "GRIME": ["horror", "soulslike", "accion", "exploracion", "atmosfera"],
  "Gris": ["summer", "cozy", "plataformas", "artístico", "narrativo"],
  "Growing Up In The Caves": ["horror", "cozy", "survival", "narrativo", "pixelart"],
  "Gunfire Reborn": ["summer", "roguelite", "shooter", "accion", "cooperativo"],

  // --- H ---
  "Hades": ["summer", "roguelite", "accion", "narrativo", "dificil"],
  "Hades II": ["summer", "roguelite", "accion", "narrativo", "dificil"],
  "Heaven's Vault": ["summer", "narrativo", "aventura", "misterio", "exploracion"],
  "Highfleet": ["strategy", "sci-fi", "accion", "gestion", "atmosfera"],
  "Hoa": ["cozy", "plataformas", "artístico", "relajante", "narrativo"],
  "Hob": ["aventura", "accion", "puzles", "exploracion", "plataformas", "indie", "singleplayer"],
  "Hokko Life": ["summer", "cozy", "simulacion", "construccion", "relajante"],
  "Hollow Knight": ["summer", "metroidvania", "soulslike", "exploracion", "dificil"],
  "Hollow Knight: Silksong": ["metroidvania", "accion", "dificil", "pixelart", "exploracion"],
  "House Flipper Remastered Collection": ["simulacion", "gestion", "construccion", "cozy", "relajante"],
  "Hue": ["puzles", "plataformas", "color", "desafío", "atmosferico", "indie", "singleplayer"],
  "Hyper Light Drifter": ["summer", "accion", "exploracion", "pixelart", "atmosfera"],
  "Hypnospace Outlaw": ["rpg", "narrativo", "misterio", "retro", "only-english"],

  // --- I ---
  "Idle Chapel": ["idle", "gestion", "simulacion", "cozy", "casual"],
  "In Rays of the Light": ["horror", "puzzle", "atmosfera", "misterio", "liminal"],
  "Indika": ["horror", "narrativo", "aventura", "atmosfera", "psicologico"],
  "Inscryption": ["horror", "strategy", "cartas", "misterio", "puzzle"],
  "Inside": ["horror", "plataformas", "puzzle", "atmosfera", "narrativo"],
  "Interdimensional Vending Machine": ["cozy", "simulacion", "gestion", "sci-fi", "humor"],
  "Iron Lung": ["horror", "sci-fi", "submarino", "tenso", "atmosfera"],
  "It Takes Two": ["summer", "cooperativo", "plataformas", "aventura", "puzzle"],

  // --- J ---
  "Jazzpunk": ["summer", "aventura", "humor", "corto", "retro"],
  "Journey": ["summer", "cozy", "exploracion", "atmosfera", "cooperativo"],
  "Judgment Apocalypse": ["strategy", "horror", "survival", "gestion", "construccion"],
  "Jusant": ["summer", "cozy", "plataformas", "exploracion", "artístico"],

  // --- K ---
  "Kairo": ["horror", "puzzle", "exploracion", "atmosfera", "liminal"],
  "Katana ZERO": ["cyberpunk", "horror", "accion", "pixelart", "narrativo"],
  "Kena: Bridge of Spirits": ["summer", "accion", "aventura", "narrativo", "cozy"],
  "Kitman": ["cozy", "strategy", "gestion", "humor", "cooperativo"],
  "Kind Words (lo fi chill beats to write to)": ["cozy", "relajante", "social", "artístico", "corto"],
  "King of Seas": ["summer", "accion", "piratas", "aventura", "rpg"],

  // --- L ---
  "Lake": ["cozy", "summer", "narrativo", "simulacion", "relajante"],
  "Last Day of June": ["puzzle", "narrativo", "relajante", "misterio", "atmosfera"],
  "Lethal Company": ["horror", "cooperativo", "multijugador", "tenso", "humor"],
  "Lil Gator Game": ["summer", "cozy", "plataformas", "aventura", "relajante"],
  "Limbo": ["horror", "plataformas", "puzzle", "atmosfera", "artístico"],
  "Limbus Company": ["rpg", "horror", "narrativo", "accion", "pixelart"],
  "Little Nightmares": ["horror", "plataformas", "atmosfera", "narrativo", "puzzle"],
  "Little Nightmares I": ["horror", "plataformas", "atmosfera", "narrativo", "puzzle"],
  "Little Nightmares II": ["horror", "plataformas", "atmosfera", "narrativo", "puzzle"],
  "Little Nightmares III": ["horror", "plataformas", "atmosfera", "narrativo", "puzzle"],
  "Littlewood": ["summer", "cozy", "simulacion", "gestion", "pixelart"],
  "Lone Survivor": ["horror", "survival", "pixelart", "misterio", "psicologico"],
  "Loop Hero": ["strategy", "horror", "summer", "roguelite", "cartas"],
  "Lorelei and the Laser Eyes": ["puzzle", "horror", "misterio", "atmosfera", "narrativo"],
  "Lunacid": ["horror", "rpg", "exploracion", "retro", "atmosfera"],

  // --- M ---
  "Mainframe Industries": ["cyberpunk", "puzzle", "hacking", "sci-fi", "only-english"],
  "Manifold Garden": ["summer", "puzzle", "artístico", "atmosfera", "exploracion"],
  "Manor Lords": ["strategy", "summer", "gestion", "construccion", "simulacion"],
  "Manual Samuel": ["summer", "humor", "aventura", "corto", "plataformas"],
  "Maseylia: Echoes of The Past": ["rpg", "aventura", "fantasia", "misterio", "narrativo"],
  "Melatonin": ["summer", "rítmico", "cozy", "relajante", "artístico"],
  "Milk inside a bag of milk": ["horror", "narrativo", "corto", "visual-novel", "only-english"],
  "Mina the Hollower": ["horror", "summer", "accion", "retro", "pixelart"],
  "Minit": ["summer", "aventura", "puzzle", "pixelart", "corto"],
  "Minute of Islands": ["aventura", "plataformas", "artístico", "narrativo", "atmosfera"],
  "Monster Train": ["strategy", "horror", "roguelite", "cartas", "dificil"],
  "Moonglow Bay": ["summer", "cozy", "pesca", "narrativo", "rpg"],
  "Moonlight Peaks": ["summer", "cozy", "simulacion", "rpg", "relajante"],
  "Moonlighter 2: The Endless Vault": ["summer", "rpg", "roguelite", "gestion", "accion"],
  "Moonscars": ["soulslike", "plataformas", "horror", "pixelart", "dificil"],
  "Moving Out 2": ["summer", "cooperativo", "humor", "accion", "plataformas"],
  "Mullet MadJack": ["cyberpunk", "summer", "accion", "shooter", "retro"],
  "Mundaun": ["horror", "puzzle", "misterio", "atmosfera", "artístico"],
  "My House.wad": ["horror", "misterio", "retro", "pixelart", "atmosfera"],
  "Myst": ["puzzle", "aventura", "misterio", "atmosfera", "exploracion"],
  "Mytich Love: Iberian Legends": ["visual-novel", "narrativo", "romance", "fantasia", "mitologia"],

  // --- N ---
  "Narita Boy": ["cyberpunk", "accion", "plataformas", "pixelart", "artístico"],
  "Neon Abyss": ["summer", "roguelite", "accion", "pixelart", "humor"],
  "Neon Abyss 2": ["summer", "roguelite", "accion", "pixelart", "cooperativo"],
  "Neon White": ["summer", "accion", "plataformas", "rítmico", "speedrun"],
  "Neva": ["accion", "plataformas", "artístico", "narrativo", "emocional"],
  "Night in the Woods": ["cozy", "narrativo", "aventura", "pixelart", "atmosfera"],
  "Nine Sols": ["rpg", "cyberpunk", "horror", "soulslike", "accion"],
  "Norco": ["horror", "narrativo", "aventura", "misterio", "atmosfera"],
  "Northern Journey": ["summer", "rpg", "exploracion", "aventura", "atmosfera"],

  // --- O ---
  "Observation": ["horror", "sci-fi", "narrativo", "misterio", "atmosfera"],
  "Ogre Chamber 2222": ["sci-fi", "horror", "puzzle", "misterio", "atmosfera"],
  "Old Man's Journey": ["narrativo", "cozy", "puzzle", "emocional", "corto"],
  "Omno": ["cozy", "aventura", "exploracion", "relajante", "atmosfera"],
  "Omori": ["horror", "cozy", "rpg", "pixelart", "narrativo"],
  "OneShot": ["cozy", "puzzle", "narrativo", "pixelart", "misterio"],
  "Opus Magnum": ["summer", "puzzle", "strategy", "creativo", "relajante"],
  "Ori and the Blind Forest": ["metroidvania", "plataformas", "aventura", "fantasia", "emotivo", "atmosferico", "indie", "singleplayer"],
  "Ori and the Will of the Wisps": ["summer", "cozy", "plataformas", "artístico", "aventura"],
  "Ostranauts": ["strategy", "cyberpunk", "survival", "simulacion", "only-english"],
  "Outbound": ["summer", "cozy", "exploracion", "aventura", "cooperativo"],
  "Outer Wilds": ["summer", "exploracion", "aventura", "misterio", "narrativo"],
  "Oxenfree": ["horror", "narrativo", "aventura", "misterio", "pixelart"],
  "Oxenfree II: Lost Signals": ["horror", "narrativo", "aventura", "misterio", "cooperativo"],

  // --- P ---
  "Pacific Drive": ["horror", "sci-fi", "summer", "survival", "atmosfera"],
  "Papers Please": ["strategy", "summer", "narrativo", "pixelart", "tenso"],
  "Party Animals": ["summer", "cooperativo", "humor", "multijugador", "accion"],
  "Pathologic 2": ["horror", "rpg", "survival", "narrativo", "atmosfera"],
  "Patrick's Parabox": ["summer", "puzzle", "dificil", "creativo", "pixelart"],
  "Pentiment": ["rpg", "horror", "narrativo", "pixelart", "historico"],
  "Pepper Grinder": ["accion", "plataformas", "retro", "pixelart", "humor"],
  "Phasmophobia": ["horror", "cooperativo", "misterio", "tenso", "multijugador"],
  "Phoenotopia Awakening": ["summer", "rpg", "aventura", "plataformas", "pixelart"],
  "Pine": ["summer", "rpg", "exploracion", "aventura", "sandbox"],
  "Planet of Lana": ["aventura", "plataformas", "artístico", "narrativo", "atmosfera"],
  "Plug & Play": ["cozy", "puzzle", "artístico", "corto", "surrealista"],
  "Pode": ["summer", "cozy", "puzzle", "cooperativo", "atmosfera"],
  "Potion Permit": ["cozy", "rpg", "summer", "simulacion", "narrativo"],
  "Pseudoregalia": ["summer", "puzzle", "plataformas", "exploracion", "pixelart"],

  // --- R ---
  "Raft": ["summer", "survival", "construccion", "exploracion", "cooperativo"],
  "Ratatan": ["summer", "accion", "rítmico", "cooperativo", "pixel"],
  "Ravenswatch": ["horror", "summer", "roguelite", "cooperativo", "accion"],
  "Remorses": ["horror", "psicologico", "misterio", "atmosfera", "tenso"],
  "Return of the Obra Dinn": ["horror", "puzzle", "misterio", "narrativo", "atmosfera"],
  "RimWorld": ["strategy", "horror", "gestion", "simulacion", "narrativo"],
  "Rivals of Aether": ["summer", "accion", "lucha", "pixelart", "competitivo"],
  "Riven": ["puzzle", "aventura", "misterio", "atmosfera", "exploracion"],
  "Rogue Legacy 2": ["summer", "rpg", "roguelite", "plataformas", "dificil"],
  "Ruiner": ["cyberpunk", "accion", "shooter", "dificil", "pixelart"],
  "Rusty Lake: Hotel": ["horror", "puzzle", "misterio", "narrativo", "surrealista"],
  "Röki": ["aventura", "cozy", "narrativo", "puzzle", "fantasia"],

  // --- S ---
  "Sable": ["summer", "exploracion", "aventura", "rpg", "atmosfera"],
  "Sail Forth": ["summer", "exploración", "aventura", "relajante", "piratas"],
  "Sailwind": ["summer", "simulacion", "exploracion", "relajante", "aventura"],
  "Salt and Sanctuary": ["horror", "soulslike", "plataformas", "dificil", "pixelart"],
  "Sanitarium": ["horror", "puzzle", "narrativo", "misterio", "atmosfera"],
  "Sayonara Wild Hearts": ["accion", "rítmico", "artístico", "narrativo", "atmosfera"],
  "Sea of Stars": ["summer", "rpg", "pixelart", "narrativo", "aventura"],
  "Season: A Letter to the Future": ["cozy", "aventura", "narrativo", "relajante", "atmosfera"],
  "Selaco": ["horror", "summer", "accion", "shooter", "retro"],
  "Shadows of Doubt": ["cyberpunk", "horror", "misterio", "detectivesco", "simulacion"],
  "Shedworksable (Sable)": ["summer", "cozy", "exploracion", "aventura", "atmosfera"],
  "Shift At Midnight": ["horror", "misterio", "simulacion", "tenso", "atmosfera"],
  "Shovel Knight": ["summer", "accion", "plataformas", "retro", "pixelart"],
  "Signalis": ["horror", "sci-fi", "misterio", "pixelart", "atmosfera"],
  "Sister Ray": ["narrativo", "aventura", "misterio", "atmosfera", "indie"],
  "Slay the Princess": ["horror", "rpg", "narrativo", "visual-novel", "misterio"],
  "Slay the Spire": ["summer", "strategy", "roguelite", "cartas", "dificil"],
  "Slay the Spire 2": ["summer", "strategy", "roguelite", "cartas", "dificil"],
  "Slime Rancher": ["cozy", "summer", "simulacion", "exploracion", "relajante"],
  "Slots & Diapers": ["humor", "simulacion", "gestion", "indie", "casual"],
  "Smushi Come Home": ["cozy", "summer", "aventura", "plataformas", "relajante"],
  "SOMA": ["horror", "sci-fi", "narrativo", "misterio", "atmosfera"],
  "Somerville": ["sci-fi", "aventura", "atmosfera", "narrativo", "emocional"],
  "Songs of Syx": ["strategy", "summer", "gestion", "construccion", "only-english"],
  "Sonic Mania": ["summer", "accion", "plataformas", "retro", "pixelart"],
  "Spiritfall": ["summer", "accion", "roguelite", "plataformas", "dificil"],
  "Spiritfarer": ["horror", "cozy", "summer", "narrativo", "gestion"],
  "Spiritfarer: Farewell Edition": ["horror", "cozy", "summer", "narrativo", "gestion"],
  //"Splatoon 3": ["accion", "multijugador", "competitivo", "humor", "shooter"],
  "Stardew Valley": ["summer", "cozy", "simulacion", "gestion", "construccion"],
  "Sticky Business": ["cozy", "summer", "simulacion", "relajante", "creativo"],
  "Strange Horticulture": ["cozy", "puzzle", "summer", "misterio", "narrativo"],
  "Stray": ["cyberpunk", "cozy", "exploracion", "narrativo", "atmosfera"],
  "Stray Gods": ["rpg", "narrativo", "rítmico", "aventura", "fantasia"],
  "Subnautica": ["horror", "summer", "survival", "exploracion", "sci-fi"],
  "Subnautica: Below Zero": ["horror", "summer", "survival", "exploracion", "sci-fi"],
  "Summerhouse": ["summer", "cozy", "construccion", "relajante", "pixelart"],
  "Superliminal": ["summer", "puzzle", "exploracion", "humor", "atmosfera"],
  "Swan Song": ["narrativo", "aventura", "misterio", "atmosfera", "emocional"],

  // --- T ---
  "Tails Noir": ["aventura", "narrativo", "detectives", "pixel-art", "cinematografico", "indie", "singleplayer"],
  "Tails of Iron": ["summer", "accion", "rpg", "narrativo", "pixelart"],
  "Tails of Iron 2: Whiskers of Winter": ["accion", "soulslike", "rpg", "narrativo", "pixelart"],
  "Tales of Seikyu": ["summer", "cozy", "simulacion", "rpg", "gestion"],
  "Tchia": ["summer", "exploracion", "aventura", "cozy", "narrativo"],
  "Terraria": ["summer", "survival", "construccion", "accion", "pixelart"],
  "Thank Goodness You're Here!": ["summer", "humor", "aventura", "corto", "artístico"],
  "The 7th Guest Remake": ["horror", "puzzle", "misterio", "retro", "atmosfera"],
  "The Adventures of Elliot: The Millenium Tales": ["rpg", "aventura", "fantasia", "narrativo", "exploracion"],
  "The Artful Escape": ["aventura", "artístico", "narrativo", "rítmico", "humor"],
  "The Binding of Isaac": ["roguelike", "accion", "disparos", "mazmorras", "gore", "indie", "singleplayer"],
  "The Cosmic Wheel Sisterhood": ["rpg", "cozy", "narrativo", "misterio", "pixelart"],
  "The Forgotten City": ["rpg", "misterio", "narrativo", "historico", "puzzle"],
  "The Garden Path": ["summer", "cozy", "simulacion", "relajante", "artístico"],
  "The Last Campfire": ["cozy", "puzzle", "narrativo", "aventura", "emocional"],
  "The Long Dark": ["horror", "summer", "survival", "exploracion", "atmosfera"],
  "The Missing: J.J. Macfield": ["horror", "plataformas", "narrativo", "puzzle", "emocional"],
  "The Outbound Ghost": ["rpg", "aventura", "narrativo", "cozy", "misterio", "exploracion", "fantasia", "emocional", "indie", "turnos"],
  "The Plucky Squire": ["aventura", "puzzle", "humor", "artístico", "narrativo"],
  "The Talos Principle": ["summer", "puzzle", "narrativo", "misterio", "filosófico"],
  "The Talos Principle 2": ["summer", "puzzle", "narrativo", "misterio", "filosófico"],
  "The Wandering Village": ["estrategia", "gestion", "survival", "cozy", "relajante"],
  "The Witness": ["summer", "puzzle", "exploracion", "misterio", "dificil"],
  "Timelie": ["puzzle", "estrategia", "misterio", "atmosfera", "relajante"],
  "Timeline": ["estrategia", "gestion", "simulador", "retro", "dificil","only-english"],
  "Tinykin": ["summer", "cozy", "plataformas", "exploracion", "aventura"],
  "TMNT: Shredder's Revenge": ["summer", "accion", "retro", "cooperativo", "plataformas"],
  "TOEM": ["summer", "cozy", "puzzle", "fotografía", "narrativo"],
  "Tormented Souls": ["horror", "puzzle", "pixelart", "survival", "retro"],
  "Tormented Souls 2": ["horror", "puzzle", "pixelart", "survival", "retro"],
  "Townscaper": ["summer", "cozy", "construccion", "relajante", "creativo"],
  "Trashy Cashy": ["gestion", "simulacion", "humor", "casual", "indie"],
  "Trine 4": ["summer", "cooperativo", "puzzle", "plataformas", "aventura"],
  "Tunic": ["summer", "puzzle", "exploracion", "soulslike", "misterio"],
  "Turing Complete": ["summer", "puzzle", "strategy", "creativo", "dificil"],
  "Turnip Boy Commits Tax Evasion": ["summer", "cozy", "aventura", "humor", "pixelart"],
  "Type Or Die": ["puzzle", "educativo", "casual", "habilidad", "indie"],

  // --- U ---
  "Ultrakill": ["summer", "accion", "shooter", "retro", "dificil"],
  "Ultros": ["metroidvania", "accion", "artístico", "exploracion", "atmosfera"],
  "Umurangi Generation": ["cyberpunk", "summer", "fotografía", "artístico", "atmosfera"],
  "Unbound: Worlds Apart": ["summer", "rpg", "plataformas", "aventura", "pixelart"],
  "Underchoice": ["horror", "misterio", "narrativo", "aventura", "pixelart"],
  "Unpacking": ["summer", "cozy", "puzzle", "narrativo", "relajante"],
  "Untitled Goose Game": ["summer", "cozy", "humor", "puzzle", "aventura"],

  // --- V ---
  "Vagante": ["horror", "roguelite", "plataformas", "pixelart", "dificil"],
  "Valheim": ["summer", "survival", "construccion", "cooperativo", "exploracion"],
  "Valor Mortis": ["horror", "cooperativo", "misterio", "exploracion", "supervivencia", "tenso", "sobrenatural"],
  "Vampire Survivors": ["summer", "roguelite", "accion", "pixelart", "relajante"],
  "Venba": ["cozy", "narrativo", "corto", "puzzle", "artístico"],
  "Viewfinder": ["summer", "puzzle", "exploracion", "creativo", "atmosfera"],
  "Void Bastards": ["sci-fi", "summer", "accion", "roguelite", "humor"],

  // --- W ---
  "Wanderburg": ["summer", "cozy", "construccion", "gestion", "relajante"],
  "Wanderstop": ["cozy", "summer", "simulacion", "narrativo", "relajante"],
  "Webfishing": ["cozy", "summer", "pesca", "cooperativo", "relajante"],
  "Weird West": ["summer", "rpg", "accion", "narrativo", "roguelite"],
  "West of Loathing": ["summer", "rpg", "humor", "narrativo", "pixelart"],
  "What Remains of Edith Finch": ["summer", "cozy", "narrativo", "exploración", "atmosfera"],
  "Who's Lila?": ["horror", "puzzle", "misterio", "narrativo", "only-english"],
  "Windbound": ["summer", "survival", "exploracion", "aventura", "relajante"],
  "Witch's Apocalyptic Journey": ["rpg", "aventura", "fantasia", "narrativo", "exploracion"],
  "Witchspire": ["accion", "fantasia", "roguelite", "pixelart", "dificil"],
  "Woodo": ["summer", "cozy", "puzzle", "construccion", "relajante"],
  "Wreckfest": ["conduccion", "destruccion", "carreras", "simulacion", "fisicas", "indie", "multijugador"],
  "Wytchwood": ["summer", "cozy", "aventura", "puzzle", "narrativo"],

  // --- X ---
  "Xanthiom 2": ["accion", "metroidvania", "pixelart", "sci-fi", "exploracion"],

  // --- Y ---
  "Yuppie Psycho": ["horror", "aventura", "pixelart", "humor", "narrativo"]
};

// Configuración visual centralizada de etiquetas para evitar repeticiones absurdas
const TAG_CONFIG = {
  'horror':       { text: '☠ terror',      class: 'gbadge-horror' },
  'summer':       { text: '☀ verano',      class: 'gbadge-summer' },
  'cozy':         { text: '🌿 cozy',        class: 'gbadge-cozy' },
  'strategy':     { text: '⚙️ estrategia',  class: 'gbadge-strategy' },
  'rpg':          { text: '📜 rol',         class: 'gbadge-rpg' },
  'cyberpunk':    { text: '🧬 cyberpunk',   class: 'gbadge-cyberpunk' },
  'puzzle':       { text: '🧩 puzle',       class: 'gbadge-cozy' },
  'sci-fi':       { text: '🚀 sci-fi',      class: 'gbadge-cyberpunk' },
  'narrativo':    { text: '📖 narrativo',   class: 'gbadge-cozy' },
  'roguelite':    { text: '🔁 roguelite',   class: 'gbadge-strategy' },
  'exploracion':  { text: '🗺 exploración', class: 'gbadge-summer' },
  'survival':     { text: '🔥 supervivencia', class: 'gbadge-horror' },
  'accion':       { text: '⚔️ acción',      class: 'gbadge-summer' },
  'pixelart':     { text: '🎮 pixel art',   class: 'gbadge-rpg' },
  'cooperativo':  { text: '🤝 coop',        class: 'gbadge-cozy' },
  'metroidvania': { text: '🗝 metroidvania', class: 'gbadge-strategy' },
  'soulslike':    { text: '💀 soulslike',   class: 'gbadge-horror' },
  'atmosfera':    { text: '🌫 atmosférico', class: 'gbadge-horror' },
  'misterio':     { text: '🔍 misterio',    class: 'gbadge-rpg' },
  'gestion':      { text: '📊 gestión',     class: 'gbadge-strategy' },
  'construccion': { text: '🏗 construcción', class: 'gbadge-strategy' },
  'simulacion':   { text: '🎲 simulación',  class: 'gbadge-cozy' },
  'relajante':    { text: '😌 relajante',   class: 'gbadge-cozy' },
  'plataformas':  { text: '🏃 plataformas', class: 'gbadge-summer' },
  'retro':        { text: '👾 retro',       class: 'gbadge-rpg' },
  'dificil':      { text: '💢 difícil',     class: 'gbadge-horror' },
  'humor':        { text: '😂 humor',       class: 'gbadge-summer' },
  'aventura':     { text: '🌄 aventura',    class: 'gbadge-summer' },
  'cartas':       { text: '🃏 cartas',      class: 'gbadge-strategy' },
  'shooter':      { text: '🔫 shooter',     class: 'gbadge-summer' },
  'artístico':    { text: '🎨 artístico',   class: 'gbadge-cozy' },
  'fotografía':   { text: '📷 fotografía',  class: 'gbadge-cozy' },
  'pesca':        { text: '🎣 pesca',       class: 'gbadge-cozy' },
  'sigilo':       { text: '🤫 sigilo',      class: 'gbadge-horror' },
  'visual-novel': { text: '📚 novela visual', class: 'gbadge-rpg' },
  'piratas':      { text: '🏴‍☠️ piratas',    class: 'gbadge-summer' },
  'emocional':    { text: '💙 emocional',   class: 'gbadge-cozy' },
  'fantasia':     { text: '✨ fantasía',    class: 'gbadge-rpg' },
  'psicologico':  { text: '🧠 psicológico', class: 'gbadge-horror' },
  'historico':    { text: '📜 histórico',   class: 'gbadge-rpg' },
  'liminal':      { text: '🚪 liminal',     class: 'gbadge-horror' },
  'speedrun':     { text: '⚡ speedrun',    class: 'gbadge-summer' },
  'rítmico':      { text: '🎵 rítmico',    class: 'gbadge-cozy' },
};

// Función única y global para extraer tags de un juego
function getTag(g) { 
  return GAME_TAGS[g] || ["summer"]; 
}

// ==========================================
// 2. BANCO DE PREGUNTAS (Q)
// ==========================================
const Q = [
  { e:"☀️", t:"¿Qué sensación buscas este verano?", o:[
    {l:"A",t:"Relax y desconexión total",g:["A Short Hike","Stardew Valley","Hokko Life","Spiritfarer","Unpacking","Coral Island","Cozy Grove","Alba: A Wildlife Adventure","Cloud Gardens","Journey","Flower","Abzû","Moonlight Peaks","Tales of Seikyu","Woodo","Eastshade","Dordogne","Strange Horticulture","Wanderstop","Bunhouse","Lake","Potion Permit","Cloudheim","Smushi Come Home","Swan Song","D-topia","Pode","Coffee Talk","Webfishing","Sticky Business","Lil Gator Game","Melatonin","Tinykin","Venba","Night in the Woods","House Flipper Remastered Collection","Beastro","Interdimensional Vending Machine","Idle Chapel","Botany Manor","Season: A Letter to the Future","Omno","Florence","Old Man's Journey","FAR: Lone Sails","FAR: Changing Tides","Röki","Assemble with Care","The Last Campfire","Gibbon: Beyond the Trees"]},
    {l:"B",t:"Misterio sutil y atmósfera absorbente",g:["Dredge","Outer Wilds","Sable","Norco","Disco Elysium","Return of the Obra Dinn","Beacon Pines","Citizen Sleeper","Hypnospace Outlaw","What Remains of Edith Finch","Gris","The Cosmic Wheel Sisterhood","Animal Well","Strange Horticulture","Pentiment","Who's Lila?","Umurangi Generation","Oxenfree","Oxenfree II: Lost Signals","Night in the Woods","Swan Song","Shift At Midnight","Maseylia: Echoes of The Past","Gastova: The Witches of Arkana","Sister Ray","Lorelei and the Laser Eyes","Blue Prince","The Forgotten City","Observation","Cocoon"]},
    {l:"C",t:"Terror puro y tensión constante",g:["Tormented Souls","Crow Country","Faith: The Unholy Trinity","Amnesia: The Bunker","Phasmophobia","Iron Lung","My House.wad","Darkwood","Signalis","The Long Dark","Lethal Company","SOMA","Subnautica","Buckshot Roulette","Gloomwood","Dusk","Selaco","Barotrauma","Pathologic 2","Mundaun","Milk inside a bag of milk","A Plague Tale: Innocence","Ravenswatch","Remorses","Cursemark","Color Fear","Don't Let It Starve","Ogre Chamber 2222","Witchspire","The 7th Guest Remake","Limbo","Inside","Bramble: The Mountain King","Little Nightmares","Fran Bow","Lone Survivor","Indika"]},
    {l:"D",t:"Acción, adrenalina y reflejos",g:["Hollow Knight","Dead Cells","Hades","Hades II","Celeste","Salt and Sanctuary","Curse of the Dead Gods","GRIME","Blasphemous","Katana ZERO","Neon White","Ultrakill","Ghostrunner 2","Mullet MadJack","Pseudoregalia","Enter the Gungeon","Rogue Legacy 2","Void Bastards","Highfleet","Akane","Dark Scrolls","Ruiner","TMNT: Shredder's Revenge","Sonic Mania","Rivals of Aether","Vampire Survivors","Spiritfall","Gombo","Neva","Carrion","Pepper Grinder"]}
  ]},
  { e:"🏖️", t:"Tu escenario ideal para perderte sería…", o:[
    {l:"A",t:"Playa e islas tropicales",g:["Dave the Diver","Hokko Life","Tchia","Subnautica","Raft","Dredge","Coral Island"]},
    {l:"B",t:"Mar y navegación (de día... y de noche)",g:["Sailwind","Dredge","Sail Forth","Raft","King of Seas","Windbound","Iron Lung","Barotrauma","Aquaria","Subnautica","Smushi Come Home","The Outbound Ghost"]},
    {l:"C",t:"Montañas y naturaleza",g:["A Short Hike","Firewatch","The Long Dark","Celeste","Alba: A Wildlife Adventure","Stardew Valley","Ori and the Will of the Wisps","Amnesia: The Bunker","Cloudheim","Mundaun","Northern Journey"]},
    {l:"D",t:"Ciudad o entorno urbano",g:["Cloudpunk","Disco Elysium","Norco","Beacon Pines","Citizen Sleeper","Hypnospace Outlaw","My House.wad","Phasmophobia","Shadows of Doubt","Stray", "Umurangi Generation", "Akane"]},
    {l:"E",t:"Fantasía y mundos imaginarios",g:["Pine","Chained Echoes","Phoenotopia Awakening","CrossCode","Ara Fell","Moonlight Peaks","Grave Seasons","Tales of Seikyu","Unbound: Worlds Apart","GRIME","Blasphemous","Nine Sols","Cassette Beasts","Arcadian Atlas","Heaven's Vault","Limbus Company","Alruna: End Of History","The Adventures of Elliot"]},
    {l:"F",t:"Lugares oscuros y perturbadores",g:["Darkwood","SOMA","Signalis","Little Nightmares II","Omori","Salt and Sanctuary","Vagante","Inscryption","Hollow Knight","Tormented Souls","Crow Country","Faith: The Unholy Trinity","Slay the Princess","Lunacid","Caves of Qud","Sanitarium","Growing Up In The Caves","Anemoiapolis","Judgment Apocalypse","Limbo","Inside","Little Nightmares","Fran Bow","Lone Survivor","Kairo","In Rays of the Light","Bramble: The Mountain King","Indika"]}
  ]},
  { e:"🎮", t:"¿Cuánto esfuerzo mental quieres dedicar?", o:[
    {l:"A",t:"Cero, solo divertirme",g:["Untitled Goose Game","Goat Simulator 3","Party Animals","Trine 4","Pseudoregalia","Ratatan","Donut County","Thank Goodness You're Here!","Jazzpunk","Mullet MadJack","Moving Out 2","TMNT: Shredder's Revenge","Manual Samuel","Accounting+","Vampire Survivors","Tinykin","Minit","Turnip Boy Commits Tax Evasion","Gombo"]},
    {l:"B",t:"Algo ligero y relajado",g:["A Short Hike","Tchia","Stardew Valley","Hokko Life","Spiritfarer","Unpacking","Coral Island","Dave the Diver","Woodo","Outbound","Cozy Grove","Lake","Summerhouse","Townscaper"]},
    {l:"C",t:"Equilibrado",g:["Dave the Diver","Firewatch","CrossCode","Outer Wilds","Subnautica","Weird West","Moonlighter 2: The Endless Vault","Citizen Sleeper","Inscryption","Phasmophobia","Crow Country","Stray","Cassette Beasts","Strange Horticulture"]},
    {l:"D",t:"Me gustan los retos",g:["Hollow Knight","Salt and Sanctuary","Curse of the Dead Gods","Vagante","GRIME","Blasphemous","Blighted","Mina the Hollower","Katana ZERO","Ghostrunner 2","Nine Sols","Loop Hero","Slay the Spire","Balatro","Chants of Sennaar","The Witness","Viewfinder","Superliminal","Patrick's Parabox","Braid","Fez","Turing Complete","Opus Magnum","Children of the Sun","Slay the Spire 2"]}
  ]},
  { e:"📖", t:"¿Qué tipo de historia prefieres?", o:[
    {l:"A",t:"Alegre y optimista",g:["Hokko Life","Tchia","A Short Hike","Spiritfarer","Coral Island","Pseudoregalia","A Hat in Time","Moonlight Peaks","Tales of Seikyu","Woodo","Wytchwood","TOEM","Dordogne","Littlewood","Garden Story","Smushi Come Home","Swan Song","Carto","Moving Out 2","Coffee Talk"]},
    {l:"B",t:"Emotiva y conmovedora, romántica",g:["Omori","Firewatch","Spiritfarer","Spiritfarer: Farewell Edition","Celeste","What Remains of Edith Finch","Gris","Beacon Pines","SOMA","Citizen Sleeper","1000xRESIST","Oxenfree","Night in the Woods","Venba","Lil Gator Game","Mytich Love: Iberian Legends","The Outbound Ghost","Neva","Florence","Endling: Extinction is Forever","Chicory: A Colorful Tale","Planet of Lana","Goodbye Volcano High","Clair Obscur: Expedition 33","FAR: Lone Sails"]},
    {l:"C",t:"Humorística y absurda",g:["Untitled Goose Game","Goat Simulator 3","Disco Elysium","West of Loathing","Thank Goodness You're Here!","Jazzpunk","Buckshot Roulette","Manual Samuel","Accounting+","Plug & Play","Gombo"]},
    {l:"D",t:"Épica y grandiosa",g:["Tails of Iron","CrossCode","Chained Echoes","Weird West","Salt and Sanctuary","Blasphemous","GRIME","Hades","Nine Sols","Arcadian Atlas","Limbus Company","Heaven's Vault","Alruna: End Of History","The Adventures of Elliot: The Millenium Tales"]},
    {l:"E",t:"Misteriosa e intrigante",g:["Outer Wilds","Dredge","Return of the Obra Dinn","Disco Elysium","Norco","Grave Seasons","Mina the Hollower","Unbound: Worlds Apart","Inscryption","Signalis","Darkwood","Hypnospace Outlaw","Doki Doki Literature Club","Tormented Souls","Crow Country","Faith: The Unholy Trinity","Iron Lung","My House.wad","Amnesia: The Bunker","Phasmophobia","Shadows of Doubt","Pentiment","Slay the Princess","Sister Ray"]}
  ]},
  { e:"🎨", t:"¿Qué estilo visual te llama más?", o:[
    {l:"A",t:"Pixel Art retro",g:["Sea of Stars","Stardew Valley","Celeste","Shovel Knight","Terraria","Dead Cells","Hollow Knight","Mina the Hollower","Unbound: Worlds Apart","Omori","Norco","Signalis","Blasphemous","Vagante","Faith: The Unholy Trinity","Loop Hero","Katana ZERO","Papers Please","Demon Turf","Arcadian Atlas","Limbus Company","Patrick's Parabox","Rivals of Aether","Xanthiom 2","Denshattack!","Witchspire","Underchoice","The 7th Guest Remake","Alruna: End Of History","Lone Survivor","Yuppie Psycho","Pepper Grinder","Moonscars"]},
    {l:"B",t:"Dibujos animados y colorido",g:["Untitled Goose Game","Tchia","Cuphead","Trine 4","Pseudoregalia","A Hat in Time","Little Nightmares II","Cult of the Lamb","A Short Hike","Cozy Grove","Smushi Come Home","Moving Out 2","Demon Turf","Pode","Chicory: A Colorful Tale","The Plucky Squire","Sayonara Wild Hearts","Neva","The Artful Escape"]},
    {l:"C",t:"Oscuro y perturbador (retro 3D o expresionista)",g:["Darkwood","SOMA","Little Nightmares II","Inscryption","Omori","Signalis","Blasphemous","GRIME","Tormented Souls","Crow Country","Amnesia: The Bunker","Iron Lung","My House.wad","Buckshot Roulette","Gloomwood","Dusk","Pathologic 2","Limbo","Inside","Little Nightmares","Bramble: The Mountain King","Indika","Lorelei and the Laser Eyes"]}
  ]},
  { e:"⚔️", t:"¿Cómo prefieres el combate o el peligro?", o:[
    {l:"A",t:"Sin combate (exploración y relax)",g:["A Short Hike","Stardew Valley","Hokko Life","Spiritfarer","Unpacking","Coral Island","Abzû","Journey","Eastshade","Norco","Citizen Sleeper","Hypnospace Outlaw","Iron Lung","Townscaper","A Little to the Left","Summerhouse","Dordogne","The Cosmic Wheel Sisterhood","Pentiment","Papers Please","Coffee Talk","Carto","Heaven's Vault"]},
    {l:"B",t:"Combate ligero y divertido",g:["Dave the Diver","Tchia","Hades","Sailwind","Pseudoregalia","A Hat in Time","Crow Country","Cult of the Lamb","Moonlighter 2: The Endless Vault","Stray","Cassette Beasts","Gombo"]},
    {l:"C",t:"Combate clásico o puzles de supervivencia",g:["Tails of Iron","CrossCode","Kena: Bridge of Spirits","Phoenotopia Awakening","Weird West","Hyper Light Drifter","Tormented Souls","My House.wad","Pacific Drive","Animal Well","Strange Horticulture"]},
    {l:"D",t:"Combate / evasión desesperada y desafiante",g:["Hollow Knight","Salt and Sanctuary","Dead Cells","Celeste","Curse of the Dead Gods","Mina the Hollower","Blighted","Vagante","GRIME","Blasphemous","Signalis","Amnesia: The Bunker","Faith: The Unholy Trinity","Phasmophobia","Darkwood","SOMA","Frostpunk 2","Against the Storm"]},
    {l:"E",t:"Combate épico y espectacular",g:["Hades","Chained Echoes","Ultrakill","Neon White","Enter the Gungeon","Rogue Legacy 2","Dead Cells","Ghostrunner 2","Katana ZERO","Mullet MadJack","Nine Sols","Akane","Ruiner","TMNT: Shredder's Revenge","Arcadian Atlas","Limbus Company","Rivals of Aether"]}
  ]},
  {
    e: "🌐", t: "¿Cómo te llevas con el idioma de Shakespeare (Inglés)?", o: [
      { l: "A", t: "No es un problema, juego en inglés perfectamente si el juego lo requiere", g: ["Who's Lila?", "Ostranauts", "Caves of Qud", "Milk inside a bag of milk", "Mainframe Industries", "Songs of Syx", "Hypnospace Outlaw", "Grave Seasons", "Disco Elysium", "Citizen Sleeper","Alruna: End Of History"] },
      { l: "B", t: "Prefiero que esté en español, pero si es de poca lectura (acción/arcade) me defiendo", g: ["Akane", "Ultrakill", "Neon White", "Katana ZERO", "Ghostrunner 2", "Dead Cells", "Hades", "Void Bastards", "Highfleet"] },
      { l: "C", t: "Nivel básico. Quiero mi juego 100% en español (o traducido por fans) para enterarme de la historia", g: ["A Short Hike", "Stardew Valley", "Sea of Stars", "Blasphemous", "Chants of Sennaar", "Dredge", "Omori", "Signalis", "Celeste", "Hollow Knight", "Unpacking", "Gris", "Spiritfarer"] }
  ]},
];
